services:
  # Laravel App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: handyman_app_service
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - storage_data:/var/www/html/storage/app/public
    networks:
      - handyman_net

  # Nginx Web Service
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: handyman_web_service
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - storage_data:/var/www/html/public/storage
    networks:
      - handyman_net
    depends_on:
      - app

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: handyman_db_service
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: handyman_service
      MYSQL_USER: handyman
      MYSQL_PASSWORD: handyman_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - dbdata:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - handyman_net

networks:
  handyman_net:
    driver: bridge

volumes:
  dbdata:
    driver: local
  storage_data:
    driver: local
